// @ts-check
'use strict';

// Catálogo LLM data-driven (nivel opencode). Fuente de verdad de los providers
// built-in y de la METADATA de cada modelo (contexto, output, tools, visión,
// razonamiento, coste, aliases). LLMProvider.js deriva de aquí el registry y
// los catálogos por proveedor. La capa remota (models.dev/api.json) enriquece
// este catálogo con modelos nuevos sin reemplazar lo curado.

// ── Roles visibles (lo que ve el usuario) ────────────────────────────────────
// Internamente el pipeline usa los modos 'fast'/'smart' (plumbing, intacto);
// en comandos y UI se muestran estos rótulos. Los aliases permiten escribir
// ambas nomenclaturas.
const ROLE_LABELS = { fast: 'Charla', smart: 'Tareas de agente' };

/** @type {Record<string, 'fast'|'smart'>} */
const ROLE_ALIASES = {
  charla: 'fast',
  chat: 'fast',
  rapido: 'fast',
  rapida: 'fast',
  fast: 'fast',
  agente: 'smart',
  tareas: 'smart',
  smart: 'smart',
  tools: 'smart',
};

/** @param {string} token */
function resolveRole(token) {
  if (!token) return null;
  const t = String(token).trim().toLowerCase();
  return ROLE_ALIASES[t] || null;
}

/**
 * @typedef {Object} ModelMeta
 * @property {string} label nombre amigable para UI
 * @property {number} context ventana de contexto (tokens)
 * @property {number} maxOutput salida máxima (tokens)
 * @property {boolean} tools soporta tool/function calling
 * @property {boolean} vision acepta imágenes
 * @property {boolean} reasoning modo razonamiento extendido
 * @property {boolean} free disponible en tier gratuito del proveedor
 * @property {{in: number, out: number}} cost USD por millón de tokens
 * @property {string[]} [aliases] nombres cortos aceptados por /model
 * @property {string[]} [roles] roles visibles en los que tiene sentido usarlo
 * @property {boolean} [remote] añadido por el catálogo remoto (models.dev)
 */

/**
 * @typedef {Object} ProviderDef
 * @property {string} id
 * @property {string} name
 * @property {string} type
 * @property {string} baseURL
 * @property {boolean} [free]
 * @property {{fast: string, smart: string}} defaults
 * @property {Record<string, ModelMeta>} models
 * @property {{fast?: number, smart?: number}} [timeoutMs]
 */

// ── Catálogo curado ───────────────────────────────────────────────────────────
// `models` es un mapa modelo → metadata. Campos:
//   label       nombre amigable para UI
//   context     ventana de contexto (tokens)
//   maxOutput   salida máxima (tokens)
//   tools       soporta tool/function calling (requisito para el agente)
//   vision      acepta imágenes
//   reasoning   modo razonamiento extendido
//   free        disponible en tier gratuito del proveedor
//   cost        { in, out } USD por millón de tokens (aprox., para la UI)
//   aliases     nombres cortos aceptados por /model
//   roles       roles visibles en los que tiene sentido usarlo
/** @type {ProviderDef[]} */
const BUILTIN_PROVIDERS = [
  {
    id: 'groq',
    name: 'Groq',
    type: 'openai',
    baseURL: 'https://api.groq.com/openai/v1',
    free: true,
    defaults: { fast: 'llama-3.1-8b-instant', smart: 'llama-3.3-70b-versatile' },
    models: {
      'llama-3.1-8b-instant': {
        label: 'Llama 3.1 8B Instant',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.05, out: 0.08 },
        aliases: ['llama8b', 'llama-3.1-8b'],
        roles: ['charla', 'tareas de agente'],
      },
      'llama-3.1-70b-versatile': {
        label: 'Llama 3.1 70B Versatile',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.59, out: 0.79 },
        aliases: ['llama70b', 'llama-3.1-70b'],
        roles: ['charla', 'tareas de agente'],
      },
      'llama-3.3-70b-versatile': {
        label: 'Llama 3.3 70B Versatile',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.59, out: 0.79 },
        aliases: ['llama3.3', 'llama-3.3-70b'],
        roles: ['charla', 'tareas de agente'],
      },
      'llama-3.2-3b-preview': {
        label: 'Llama 3.2 3B Preview',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['llama3b'],
        roles: ['charla'],
      },
      'llama-3.2-11b-vision-preview': {
        label: 'Llama 3.2 11B Vision Preview',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.18, out: 0.18 },
        aliases: ['llama11b-vision'],
        roles: ['charla', 'imágenes'],
      },
      'llama-3.2-90b-vision-preview': {
        label: 'Llama 3.2 90B Vision Preview',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.9, out: 0.9 },
        aliases: ['llama90b-vision'],
        roles: ['charla', 'imágenes'],
      },
      'gemma2-9b-it': {
        label: 'Gemma 2 9B IT',
        context: 8192,
        maxOutput: 8192,
        tools: false,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['gemma2-9b'],
        roles: ['charla'],
      },
      'gemma2-27b-it': {
        label: 'Gemma 2 27B IT',
        context: 8192,
        maxOutput: 8192,
        tools: false,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['gemma2-27b'],
        roles: ['charla'],
      },
      'mixtral-8x7b-32768': {
        label: 'Mixtral 8x7B (32k)',
        context: 32768,
        maxOutput: 4096,
        tools: false,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.24, out: 0.24 },
        aliases: ['mixtral'],
        roles: ['charla'],
      },
      'deepseek-r1-distill-llama-70b': {
        label: 'DeepSeek R1 Distill (Llama 70B)',
        context: 131072,
        maxOutput: 4096,
        tools: false,
        vision: false,
        reasoning: true,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['deepseek-r1', 'r1-distill'],
        roles: ['charla'],
      },
      'openai/gpt-oss-120b': {
        label: 'OpenAI GPT-OSS 120B',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['gpt-oss-120b'],
        roles: ['charla', 'tareas de agente'],
      },
      'openai/gpt-oss-20b': {
        label: 'OpenAI GPT-OSS 20B',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['gpt-oss-20b'],
        roles: ['charla', 'tareas de agente'],
      },
    },
  },

  {
    id: 'gemini',
    name: 'Google Gemini',
    type: 'gemini',
    baseURL: 'https://generativelanguage.googleapis.com/v1beta',
    free: true,
    defaults: { fast: 'gemini-2.5-flash', smart: 'gemini-2.5-flash' },
    models: {
      'gemini-2.0-flash': {
        label: 'Gemini 2.0 Flash',
        context: 1048576,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.1, out: 0.4 },
        aliases: ['2.0-flash', 'flash-2.0'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'gemini-2.0-flash-lite': {
        label: 'Gemini 2.0 Flash Lite',
        context: 1048576,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.075, out: 0.3 },
        aliases: ['flash-lite', '2.0-lite'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'gemini-2.0-pro': {
        label: 'Gemini 2.0 Pro',
        context: 2097152,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 1.25, out: 5.0 },
        aliases: ['2.0-pro', 'pro-2.0'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'gemini-2.5-flash': {
        label: 'Gemini 2.5 Flash',
        context: 1048576,
        maxOutput: 65536,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.3, out: 2.5 },
        aliases: ['2.5-flash', 'flash-2.5'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'gemini-2.5-pro': {
        label: 'Gemini 2.5 Pro',
        context: 2097152,
        maxOutput: 65536,
        tools: true,
        vision: true,
        reasoning: true,
        free: true,
        cost: { in: 1.25, out: 10.0 },
        aliases: ['2.5-pro', 'pro-2.5'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'gemini-1.5-flash': {
        label: 'Gemini 1.5 Flash',
        context: 1048576,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.075, out: 0.3 },
        aliases: ['1.5-flash', 'flash-1.5'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'gemini-1.5-flash-8b': {
        label: 'Gemini 1.5 Flash 8B',
        context: 1048576,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.0375, out: 0.15 },
        aliases: ['1.5-flash-8b'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'gemini-1.5-pro': {
        label: 'Gemini 1.5 Pro',
        context: 2097152,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 1.25, out: 5.0 },
        aliases: ['1.5-pro', 'pro-1.5'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
    },
  },

  {
    id: 'openai',
    name: 'OpenAI',
    type: 'openai',
    baseURL: 'https://api.openai.com/v1',
    free: false,
    defaults: { fast: 'gpt-4o-mini', smart: 'gpt-4o-mini' },
    models: {
      'gpt-4o-mini': {
        label: 'GPT-4o mini',
        context: 128000,
        maxOutput: 16384,
        tools: true,
        vision: true,
        reasoning: false,
        free: false,
        cost: { in: 0.15, out: 0.6 },
        aliases: ['4o-mini', 'gpt4o-mini'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'gpt-4o': {
        label: 'GPT-4o',
        context: 128000,
        maxOutput: 16384,
        tools: true,
        vision: true,
        reasoning: false,
        free: false,
        cost: { in: 2.5, out: 10.0 },
        aliases: ['gpt4o'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'gpt-4.1-mini': {
        label: 'GPT-4.1 mini',
        context: 1048576,
        maxOutput: 32768,
        tools: true,
        vision: true,
        reasoning: false,
        free: false,
        cost: { in: 0.4, out: 1.6 },
        aliases: ['4.1-mini'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'gpt-4.1': {
        label: 'GPT-4.1',
        context: 1048576,
        maxOutput: 32768,
        tools: true,
        vision: true,
        reasoning: false,
        free: false,
        cost: { in: 2.0, out: 8.0 },
        aliases: ['gpt4.1'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'gpt-4.1-nano': {
        label: 'GPT-4.1 nano',
        context: 1048576,
        maxOutput: 32768,
        tools: true,
        vision: true,
        reasoning: false,
        free: false,
        cost: { in: 0.1, out: 0.4 },
        aliases: ['4.1-nano'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'gpt-4-turbo': {
        label: 'GPT-4 Turbo',
        context: 128000,
        maxOutput: 4096,
        tools: true,
        vision: true,
        reasoning: false,
        free: false,
        cost: { in: 10.0, out: 30.0 },
        aliases: ['gpt4-turbo'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'gpt-4': {
        label: 'GPT-4',
        context: 8192,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: false,
        cost: { in: 30.0, out: 60.0 },
        aliases: ['gpt4'],
        roles: ['charla', 'tareas de agente'],
      },
      'o3-mini': {
        label: 'o3-mini',
        context: 200000,
        maxOutput: 100000,
        tools: true,
        vision: true,
        reasoning: true,
        free: false,
        cost: { in: 1.1, out: 4.4 },
        aliases: ['o3-mini'],
        roles: ['tareas de agente'],
      },
      'o4-mini': {
        label: 'o4-mini',
        context: 200000,
        maxOutput: 100000,
        tools: true,
        vision: true,
        reasoning: true,
        free: false,
        cost: { in: 1.1, out: 4.4 },
        aliases: ['o4-mini'],
        roles: ['tareas de agente'],
      },
      'gpt-5': {
        label: 'GPT-5',
        context: 400000,
        maxOutput: 100000,
        tools: true,
        vision: true,
        reasoning: true,
        free: false,
        cost: { in: 1.25, out: 10.0 },
        aliases: ['gpt5'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'gpt-5-mini': {
        label: 'GPT-5 mini',
        context: 400000,
        maxOutput: 100000,
        tools: true,
        vision: true,
        reasoning: true,
        free: false,
        cost: { in: 0.25, out: 2.0 },
        aliases: ['gpt5-mini'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
    },
  },

  {
    id: 'anthropic',
    name: 'Anthropic',
    type: 'anthropic',
    baseURL: 'https://api.anthropic.com/v1',
    free: false,
    defaults: { fast: 'claude-3-haiku-20240307', smart: 'claude-3-sonnet-20240229' },
    models: {
      'claude-3-haiku-20240307': {
        label: 'Claude 3 Haiku',
        context: 200000,
        maxOutput: 4096,
        tools: true,
        vision: true,
        reasoning: false,
        free: false,
        cost: { in: 0.25, out: 1.25 },
        aliases: ['haiku'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'claude-3-sonnet-20240229': {
        label: 'Claude 3 Sonnet',
        context: 200000,
        maxOutput: 4096,
        tools: true,
        vision: true,
        reasoning: false,
        free: false,
        cost: { in: 3.0, out: 15.0 },
        aliases: ['sonnet'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'claude-3-opus-20240229': {
        label: 'Claude 3 Opus',
        context: 200000,
        maxOutput: 4096,
        tools: true,
        vision: true,
        reasoning: false,
        free: false,
        cost: { in: 15.0, out: 75.0 },
        aliases: ['opus'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'claude-3-5-haiku-latest': {
        label: 'Claude 3.5 Haiku',
        context: 200000,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: false,
        cost: { in: 0.8, out: 4.0 },
        aliases: ['3.5-haiku'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'claude-3-5-sonnet-latest': {
        label: 'Claude 3.5 Sonnet',
        context: 200000,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: false,
        cost: { in: 3.0, out: 15.0 },
        aliases: ['3.5-sonnet'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'claude-3-7-sonnet-latest': {
        label: 'Claude 3.7 Sonnet',
        context: 200000,
        maxOutput: 64000,
        tools: true,
        vision: true,
        reasoning: true,
        free: false,
        cost: { in: 3.0, out: 15.0 },
        aliases: ['3.7-sonnet'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'claude-4-sonnet': {
        label: 'Claude 4 Sonnet',
        context: 1000000,
        maxOutput: 64000,
        tools: true,
        vision: true,
        reasoning: true,
        free: false,
        cost: { in: 3.0, out: 15.0 },
        aliases: ['4-sonnet', 'sonnet-4'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'claude-4-opus': {
        label: 'Claude 4 Opus',
        context: 1000000,
        maxOutput: 64000,
        tools: true,
        vision: true,
        reasoning: true,
        free: false,
        cost: { in: 15.0, out: 75.0 },
        aliases: ['4-opus', 'opus-4'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
    },
  },

  {
    id: 'xai',
    name: 'xAI (Grok)',
    type: 'openai',
    baseURL: 'https://api.x.ai/v1',
    free: false,
    defaults: { fast: 'grok-beta', smart: 'grok-beta' },
    models: {
      'grok-beta': {
        label: 'Grok Beta',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: false,
        cost: { in: 5.0, out: 15.0 },
        aliases: ['grok'],
        roles: ['charla', 'tareas de agente'],
      },
      'grok-2': {
        label: 'Grok 2',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: false,
        cost: { in: 2.0, out: 10.0 },
        aliases: ['grok2'],
        roles: ['charla', 'tareas de agente'],
      },
      'grok-2-1212': {
        label: 'Grok 2 1212',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: false,
        cost: { in: 2.0, out: 10.0 },
        aliases: ['grok2-1212'],
        roles: ['charla', 'tareas de agente'],
      },
      'grok-3': {
        label: 'Grok 3',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: true,
        free: false,
        cost: { in: 3.0, out: 15.0 },
        aliases: ['grok3'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'grok-3-mini': {
        label: 'Grok 3 mini',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: true,
        free: false,
        cost: { in: 0.3, out: 0.5 },
        aliases: ['grok3-mini'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'grok-3-fast': {
        label: 'Grok 3 Fast',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: true,
        free: false,
        cost: { in: 0.6, out: 4.0 },
        aliases: ['grok3-fast'],
        roles: ['charla', 'tareas de agente'],
      },
    },
  },

  {
    id: 'nvidia',
    name: 'NVIDIA Builds',
    type: 'openai',
    baseURL: 'https://integrate.api.nvidia.com/v1',
    free: true,
    timeoutMs: { fast: 45_000, smart: 120_000 },
    defaults: { fast: 'openai/gpt-oss-20b', smart: 'minimaxai/minimax-m3' },
    models: {
      'meta/llama-3.3-70b-instruct': {
        label: 'Llama 3.3 70B Instruct',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.59, out: 0.79 },
        aliases: ['nvidia-llama3.3'],
        roles: ['charla', 'tareas de agente'],
      },
      'meta/llama-3.1-70b-instruct': {
        label: 'Llama 3.1 70B Instruct',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.59, out: 0.79 },
        aliases: ['nvidia-llama70b'],
        roles: ['charla', 'tareas de agente'],
      },
      'meta/llama-3.1-8b-instruct': {
        label: 'Llama 3.1 8B Instruct',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.05, out: 0.08 },
        aliases: ['nvidia-llama8b'],
        roles: ['charla', 'tareas de agente'],
      },
      'meta/llama-3.2-11b-vision-instruct': {
        label: 'Llama 3.2 11B Vision Instruct',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.18, out: 0.18 },
        aliases: ['nvidia-llama-vision'],
        roles: ['charla', 'imágenes'],
      },
      'mistralai/mistral-large-2-instruct': {
        label: 'Mistral Large 2 Instruct',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 2.0, out: 6.0 },
        aliases: ['mistral-large'],
        roles: ['charla', 'tareas de agente'],
      },
      'mistralai/mixtral-8x22b-v0.1': {
        label: 'Mixtral 8x22B',
        context: 65536,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.9, out: 0.9 },
        aliases: ['mixtral-8x22b'],
        roles: ['charla', 'tareas de agente'],
      },
      'minimaxai/minimax-m3': {
        label: 'MiniMax M3',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: true,
        free: true,
        cost: { in: 1.0, out: 8.0 },
        aliases: ['minimax-m3', 'm3'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'nvidia/nemotron-3-nano-30b-a3b': {
        label: 'Nemotron 3 Nano 30B',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.1, out: 0.4 },
        aliases: ['nemotron-nano'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'nvidia/nemotron-3-super-120b-a12b': {
        label: 'Nemotron 3 Super 120B',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.4, out: 1.6 },
        aliases: ['nemotron-super'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'nvidia/llama-3.3-nemotron-super-49b-v1.5': {
        label: 'Nemotron Super 49B (Llama 3.3)',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.4, out: 1.6 },
        aliases: ['nemotron-49b'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'openai/gpt-oss-120b': {
        label: 'OpenAI GPT-OSS 120B',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['nvidia-gpt-oss-120b'],
        roles: ['charla', 'tareas de agente'],
      },
      'openai/gpt-oss-20b': {
        label: 'OpenAI GPT-OSS 20B',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['nvidia-gpt-oss-20b'],
        roles: ['charla', 'tareas de agente'],
      },
      'z-ai/glm-5.2': {
        label: 'Z-AI GLM 5.2',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.2, out: 0.4 },
        aliases: ['glm-5.2', 'glm'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'stepfun-ai/step-3.7-flash': {
        label: 'StepFun Step 3.7 Flash',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.2, out: 0.4 },
        aliases: ['step-3.7'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'google/gemma-3-12b-it': {
        label: 'Gemma 3 12B IT',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['gemma3-12b'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'google/gemma-3-4b-it': {
        label: 'Gemma 3 4B IT',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['gemma3-4b'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'google/gemma-4-31b-it': {
        label: 'Gemma 4 31B IT',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: true,
        reasoning: false,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['gemma4-31b'],
        roles: ['charla', 'tareas de agente', 'imágenes'],
      },
      'ai21labs/jamba-1.5-large-instruct': {
        label: 'AI21 Jamba 1.5 Large',
        context: 256000,
        maxOutput: 4096,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.2, out: 0.4 },
        aliases: ['jamba'],
        roles: ['charla', 'tareas de agente'],
      },
    },
  },

  {
    id: 'huggingface',
    name: 'Hugging Face',
    type: 'openai',
    baseURL: 'https://api-inference.huggingface.co/v1',
    free: true,
    defaults: {
      fast: 'meta-llama/Llama-3.2-3B-Instruct',
      smart: 'meta-llama/Llama-3.3-70B-Instruct',
    },
    models: {
      'meta-llama/Llama-3.2-3B-Instruct': {
        label: 'Llama 3.2 3B Instruct',
        context: 131072,
        maxOutput: 4096,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['hf-llama3b'],
        roles: ['charla', 'tareas de agente'],
      },
      'meta-llama/Llama-3.3-70B-Instruct': {
        label: 'Llama 3.3 70B Instruct',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['hf-llama70b'],
        roles: ['charla', 'tareas de agente'],
      },
      'mistralai/Mistral-7B-Instruct-v0.3': {
        label: 'Mistral 7B Instruct',
        context: 32768,
        maxOutput: 4096,
        tools: false,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['hf-mistral7b'],
        roles: ['charla'],
      },
      'google/gemma-2-27b-it': {
        label: 'Gemma 2 27B IT',
        context: 8192,
        maxOutput: 4096,
        tools: false,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['hf-gemma2'],
        roles: ['charla'],
      },
      'Qwen/Qwen2.5-7B-Instruct': {
        label: 'Qwen 2.5 7B Instruct',
        context: 32768,
        maxOutput: 4096,
        tools: false,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.0, out: 0.0 },
        aliases: ['hf-qwen'],
        roles: ['charla'],
      },
    },
  },

  {
    id: 'deepseek',
    name: 'DeepSeek',
    type: 'openai',
    baseURL: 'https://api.deepseek.com/v1',
    free: true,
    defaults: { fast: 'deepseek-chat', smart: 'deepseek-chat' },
    models: {
      'deepseek-chat': {
        label: 'DeepSeek Chat',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.27, out: 1.1 },
        aliases: ['chat', 'ds-chat'],
        roles: ['charla', 'tareas de agente'],
      },
      'deepseek-reasoner': {
        label: 'DeepSeek Reasoner',
        context: 131072,
        maxOutput: 8192,
        tools: false,
        vision: false,
        reasoning: true,
        free: true,
        cost: { in: 0.55, out: 2.19 },
        aliases: ['reasoner', 'ds-r1'],
        roles: ['charla'],
      },
      'deepseek-v3.1': {
        label: 'DeepSeek V3.1',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.27, out: 1.1 },
        aliases: ['v3.1'],
        roles: ['charla', 'tareas de agente'],
      },
      'deepseek-r1': {
        label: 'DeepSeek R1',
        context: 131072,
        maxOutput: 8192,
        tools: false,
        vision: false,
        reasoning: true,
        free: true,
        cost: { in: 0.55, out: 2.19 },
        aliases: ['r1'],
        roles: ['charla'],
      },
      'deepseek-v4': {
        label: 'DeepSeek V4',
        context: 131072,
        maxOutput: 8192,
        tools: true,
        vision: false,
        reasoning: false,
        free: true,
        cost: { in: 0.27, out: 1.1 },
        aliases: ['v4'],
        roles: ['charla', 'tareas de agente'],
      },
    },
  },
];

// ── Helpers ───────────────────────────────────────────────────────────────────

/** @param {string} id */
function getProviderDef(id) {
  return BUILTIN_PROVIDERS.find((p) => p.id === id) || null;
}

/** @param {string} providerId @param {string} modelId */
function getModelMeta(providerId, modelId) {
  const p = getProviderDef(providerId);
  return (p && p.models[modelId]) || null;
}

/**
 * Resuelve un token a un id de modelo de un provider: id exacto, alias o
 * substring (case-insensitive). Devuelve null si no hay coincidencia.
 * @param {string} providerId
 * @param {string} token
 */
function resolveModelId(providerId, token) {
  const p = getProviderDef(providerId);
  if (!p || !token) return null;
  const t = String(token).trim().toLowerCase();
  if (p.models[t]) return t;
  for (const [id, meta] of Object.entries(p.models)) {
    if (meta.aliases && meta.aliases.some((a) => a.toLowerCase() === t)) return id;
  }
  return Object.keys(p.models).find((id) => id.toLowerCase().includes(t)) || null;
}

/**
 * Shape histórico { providerId: [modelId...] } — lo usaba MODEL_CATALOG y lo
 * siguen usando los tests. Se deriva del catálogo (una sola fuente de verdad).
 * @returns {Record<string, string[]>}
 */
function deriveModelCatalog() {
  /** @type {Record<string, string[]>} */
  const out = {};
  for (const p of BUILTIN_PROVIDERS) out[p.id] = Object.keys(p.models);
  return out;
}

module.exports = {
  BUILTIN_PROVIDERS,
  ROLE_LABELS,
  ROLE_ALIASES,
  resolveRole,
  getProviderDef,
  getModelMeta,
  resolveModelId,
  deriveModelCatalog,
};
