// @ts-nocheck
'use strict';

// GestureLexicon — vocabulario multilingüe de estados de ánimo/acciones que el
// asistente puede expresar con el modelo Live2D. El usuario aprobó extender el
// vocabulario: 6 emociones TTS (happy/excited/sad/tired/gentle/default) +
// angry/surprised/shy/think, más acciones (wave/nod/shake/dance/sing/photo/
// wink/sleep) para las animaciones que traen los modelos.
//
// Cada mood canónico tiene sinónimos en ES/EN/中文/日本語 (+romaji) con los que
// se buscan los gestos reales del modelo (nombres de .exp3.json/.motion3.json
// o los Name referenciados en el model3.json).

const MOODS = [
  'happy',
  'excited',
  'sad',
  'angry',
  'surprised',
  'shy',
  'tired',
  'think',
  'gentle',
  'default',
  'cry',
  'laugh',
  'blush',
  'panic',
  'wave',
  'nod',
  'shake',
  'dance',
  'sing',
  'photo',
  'wink',
  'sleep',
];

const ALIASES = {
  happy: [
    'happy',
    'joy',
    'joyful',
    'glad',
    'cheerful',
    'smile',
    'laugh',
    'laughing',
    'feliz',
    'alegre',
    'contento',
    'sonrisa',
    '开心',
    '高兴',
    '快乐',
    '笑',
    '微笑',
    '比耶',
    '嬉しい',
    '幸せ',
    '笑顔',
    'にこにこ',
    'hehe',
    'yay',
    'lol',
    'waku',
    'wawa',
    'mua',
    'kiss',
  ],
  excited: [
    'excited',
    'excitement',
    'hype',
    'energetic',
    'pumped',
    'enthusiastic',
    'emocionado',
    'entusiasmado',
    'animado',
    '兴奋',
    '激动',
    '哇',
    '星星',
    '闪光',
    'わくわく',
    'テンション',
    '興奮',
    'ときめき',
    'sparkle',
    'stars',
    'kira',
    'kya',
    'aaaa',
    'wow',
  ],
  sad: [
    'sad',
    'sadness',
    'unhappy',
    'sorrow',
    'melancholy',
    'down',
    'triste',
    'tristeza',
    'apenado',
    '悲伤',
    '伤心',
    '难过',
    '委屈',
    '悲しい',
    '切ない',
    '哀しい',
  ],
  angry: [
    'angry',
    'anger',
    'mad',
    'furious',
    'fury',
    'annoyed',
    'irritated',
    'rage',
    'enfadado',
    'enojado',
    'furioso',
    'molesto',
    'cabreado',
    'enfado',
    '生气',
    '愤怒',
    '怒',
    '黑脸',
    '白眼',
    '恼',
    '怒る',
    '腹立つ',
    'むかつく',
    'ムカムカ',
    'いらいら',
  ],
  surprised: [
    'surprised',
    'surprise',
    'shock',
    'shocked',
    'amazed',
    'startled',
    'wow',
    'sorpresa',
    'sorprendido',
    'asombrado',
    'impresionado',
    '惊讶',
    '震惊',
    '吃惊',
    '惊',
    '慌张',
    '流汗',
    'びっくり',
    '驚き',
    'おどろき',
    '驚く',
    'big eyes',
    'wide eyes',
    'sweat',
  ],
  shy: [
    'shy',
    'shyness',
    'embarrassed',
    'bashful',
    'timid',
    'tímido',
    'timidez',
    'vergüenza',
    'sonrojarse',
    'apocado',
    '害羞',
    '脸红',
    '捂脸',
    '脸红红',
    '害臊',
    '恥ずかしい',
    '照れ',
    'はにかみ',
    '照れる',
    'blush',
    'blushing',
    'blushy',
  ],
  tired: [
    'tired',
    'fatigue',
    'exhausted',
    'weary',
    'sleepy',
    'sleepyhead',
    'cansado',
    'agotado',
    'fatiga',
    'soñoliento',
    '累',
    '困',
    '疲惫',
    '疲',
    '睡觉',
    '瞌睡',
    '困倦',
    '枕头',
    '打盹',
    '眠い',
    'ねむい',
    '疲れた',
    'くたびれた',
    'keshui',
    'zhentou',
    'zzz',
  ],
  think: [
    'think',
    'thinking',
    'thought',
    'ponder',
    'musing',
    'curious',
    'curiosity',
    'pensar',
    'pensando',
    'curioso',
    'reflexionando',
    '思考',
    '想',
    '好奇',
    '疑问',
    '琢磨',
    '寻思',
    '考える',
    '思う',
    'かんがえ',
    '気になる',
    'haoqi',
  ],
  gentle: [
    'gentle',
    'soft',
    'tender',
    'kind',
    'warm',
    'calm',
    'serene',
    'soothing',
    'suave',
    'tierno',
    'amable',
    'tranquilo',
    'calmado',
    '温柔',
    '温和',
    '温婉',
    '優しい',
    '穏やか',
    'やさしい',
    'yasashii',
  ],
  default: [
    'default',
    'neutral',
    'normal',
    'relax',
    'relaxed',
    'natural',
    'serious',
    'por defecto',
    'normal',
    'relajado',
    'serio',
    '默认',
    '平常',
    '普通',
    '淡然',
    '平静',
    '正经',
    '普通',
    'いつも',
    'フツー',
  ],
  cry: [
    'cry',
    'crying',
    'tears',
    'tear',
    'sob',
    'weep',
    'llorar',
    'llanto',
    'llorando',
    'lágrimas',
    '哭',
    '哭泣',
    '流泪',
    '泪',
    '泣く',
    '泣き',
    'なみだ',
    '涙',
  ],
  laugh: [
    'laugh',
    'laughing',
    'laughter',
    'risa',
    'reír',
    'riendo',
    '笑',
    '大笑',
    '爆笑',
    '笑う',
    '爆笑',
    'haha',
    'jaja',
    'lmao',
  ],
  blush: [
    'blush',
    'blushing',
    'rubor',
    'sonrojo',
    'sonrojarse',
    '脸红',
    '害羞',
    '照れ',
    '赤面',
    'はじか',
  ],
  panic: [
    'panic',
    'panicked',
    'panicking',
    'nervous',
    'flustered',
    'pánico',
    'asustado',
    'nervioso',
    'agobiado',
    '慌张',
    '慌乱',
    '惊慌',
    '紧张',
    '手忙脚乱',
    '慌てる',
    'あわてる',
    'パニック',
    '動揺',
  ],
  wave: [
    'wave',
    'waving',
    'greet',
    'greeting',
    'hello',
    'hi',
    'hola',
    'hola!',
    '挥手',
    '招手',
    '你好',
    '打招呼',
    '手を振る',
    'てをふる',
    'こんにちは',
    'おはよう',
  ],
  nod: ['nod', 'nodding', 'agree', 'asentir', '点头', '同意', 'うなずく', '頷く', 'はーい'],
  shake: [
    'shake',
    'headshake',
    'shaking',
    'deny',
    'disagree',
    'no',
    'reject',
    'negar',
    'negarse',
    'rechazar',
    '摇头',
    '否定',
    '首を振る',
    'くびをふる',
    'いやいや',
    'yaotou',
  ],
  dance: [
    'dance',
    'dancing',
    'spin',
    'spinning',
    'boogie',
    'danza',
    'bailar',
    'bailando',
    'giro',
    '舞蹈',
    '跳舞',
    '舞动',
    '旋转',
    '踊る',
    'ダンス',
    'おどる',
  ],
  sing: [
    'sing',
    'singing',
    'song',
    'singer',
    'canto',
    'cantar',
    'cantando',
    '唱歌',
    '歌唱',
    '唱',
    '歌',
    '歌う',
    'うた',
    'うたう',
    'シンガー',
  ],
  photo: [
    'photo',
    'picture',
    'camera',
    'selfie',
    'fotografía',
    'foto',
    'cámara',
    '照相',
    '拍照',
    '照片',
    '自拍',
    'カメラ',
    '写真',
    'しゃしん',
    '撮影',
    'zhaoxiang',
  ],
  wink: [
    'wink',
    'winking',
    'blink',
    'blinking',
    'guiño',
    'guiñar',
    '眨眼',
    '挤眼',
    'wink',
    'ウインク',
    'まばたき',
    'ぱちぱち',
    'zhaiyan',
  ],
  sleep: [
    'sleep',
    'sleeping',
    'nap',
    'siesta',
    'dormir',
    'dormido',
    'dream',
    '睡觉',
    '睡眠',
    '入睡',
    '打盹',
    '瞌睡',
    '眠る',
    'ねむる',
    '睡眠',
    'keshui',
  ],
};

// Palabras estructurales que aparecen en los nombres de gestos pero no aportan
// semántica de estado de ánimo — se ignoran al puntuar.
const NOISE = new Set([
  'idle',
  'animation',
  'anim',
  'motion',
  'motions',
  'exp',
  'expression',
  'scene',
  'model',
  'default',
  'neutral',
  'normal',
  'miku',
  'lipsync',
  'lip',
  'sync',
  'blink',
  'character',
  'behaviour',
  'behavior',
]);

// Moods que apuntan a acciones → en empate se prefiere una motion a una expresión.
const ACTION_MOODS = new Set(['wave', 'nod', 'shake', 'dance', 'sing', 'photo', 'wink', 'sleep']);

// Índice inverso: token normalizado → conjunto de moods.
const _TOKEN_MOODS = new Map();
for (const [mood, tokens] of Object.entries(ALIASES)) {
  for (const token of tokens) {
    const norm = normalizeToken(token);
    if (!norm) continue;
    if (!_TOKEN_MOODS.has(norm)) _TOKEN_MOODS.set(norm, new Set());
    _TOKEN_MOODS.get(norm).add(mood);
  }
}

// Forma canónica para comparar: minúsculas + NFKC, espacios colapsados.
// Conserva caracteres CJK tal cual.
function normalizeToken(s) {
  return String(s || '')
    .toLowerCase()
    .normalize('NFKC')
    .trim()
    .replace(/[\s_\-.]+/g, ' ');
}

function tokensFor(mood) {
  return (ALIASES[mood] || []).map(normalizeToken).filter(Boolean);
}

function moodOfToken(token) {
  const norm = normalizeToken(token);
  return _TOKEN_MOODS.get(norm) ? [..._TOKEN_MOODS.get(norm)] : [];
}

function isNoise(word) {
  return NOISE.has(normalizeToken(word));
}

function isActionMood(mood) {
  return ACTION_MOODS.has(mood);
}

function hasMood(mood) {
  return Object.prototype.hasOwnProperty.call(ALIASES, mood);
}

module.exports = {
  MOODS,
  ALIASES,
  NOISE,
  ACTION_MOODS,
  normalizeToken,
  tokensFor,
  moodOfToken,
  isNoise,
  isActionMood,
  hasMood,
};
